In [1]:
import numpy as np

In [2]:
numbers = np.arange(1, 6)

In [3]:
numbers

array([1, 2, 3, 4, 5])

In [4]:
numbers * 2

array([ 2,  4,  6,  8, 10])

In [5]:
numbers ** 3

array([  1,   8,  27,  64, 125])

In [6]:
numbers

array([1, 2, 3, 4, 5])

In [7]:
numbers += 10

In [8]:
numbers

array([11, 12, 13, 14, 15])

In [9]:
numbers * [2,2,2,2,2]

array([22, 24, 26, 28, 30])

In [10]:
numbers2 = np.linspace(1.1,5.5, 5)

In [11]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [12]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [13]:
numbers >= 13

array([False, False,  True,  True,  True])

In [14]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [15]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [16]:
numbers == numbers2

array([False, False, False, False, False])

In [17]:
numbers == numbers

array([ True,  True,  True,  True,  True])

In [18]:
np.arange(1, 6) ** 2


array([ 1,  4,  9, 16, 25])

In [19]:
grades = np.array([[87, 96, 70], [100, 87, 90], [94, 77, 90], [100, 81, 82]])
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [22]:
grades.sum()

1054

grades.min() 

In [23]:
grades.min()

70

In [24]:
grades.max()

100

In [25]:
grades.mean()

87.83333333333333

In [26]:
grades.std()

8.792357792739987

In [27]:
grades.var()

77.30555555555556

In [28]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [29]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [30]:
grades = np.random.randint(60, 101, 12).reshape(3, 4)

In [31]:
grades

array([[65, 61, 81, 65],
       [87, 70, 87, 74],
       [80, 96, 98, 79]])

In [32]:
grades.mean()

78.58333333333333

In [33]:
grades.mean(axis=0)

array([77.33333333, 75.66666667, 88.66666667, 72.66666667])

In [34]:
grades.mean(axis=1)

array([68.  , 79.5 , 88.25])